from flask import Flask, request, send_file
import os
import subprocess
import shutil
import tempfile

app = Flask(__name__)

# 模板檔案在 Docker 容器內的固定路徑
TEMPLATE_DIR = '/app' 

@app.route('/convert', methods=['POST'])
def convert():
    # 1. 建立「用完即焚」的臨時工作資料夾
    job_dir = tempfile.mkdtemp() 
    
    try:
        # 2. 建立必要資料夾
        os.makedirs(os.path.join(job_dir, "Figure"), exist_ok=True)
        os.makedirs(os.path.join(job_dir, "sections"), exist_ok=True)

        # 3. 儲存 Markdown 檔案
        if 'md_file' not in request.files:
            return "Missing md_file", 400
        md_file = request.files['md_file']
        md_file.save(os.path.join(job_dir, "paper.md"))

        # 4. 儲存圖片檔案
        figures = request.files.getlist('figures')
        for fig in figures:
            if fig.filename:
                fig.save(os.path.join(job_dir, "Figure", fig.filename))

        # 5. 生成 metadata.tex (加入關鍵詞支援)
        form = request.form
        metadata_content = f"""
% Auto-generated by Project Synapse
\\newcommand\\MyTitleZh{{{form.get('title_zh', '')}}}
\\newcommand\\MyTitleEn{{{form.get('title_en', '')}}}
\\newcommand\\MyAuthorZh{{{form.get('author_zh', '')}}}
\\newcommand\\MyAuthorEn{{{form.get('author_en', '')}}}
\\newcommand\\MyAbstractZh{{{form.get('abstract_zh', '')}}}
\\newcommand\\MyAbstractEn{{{form.get('abstract_en', '')}}}
\\newcommand\\MyKeywordsZh{{{form.get('keywords_zh', '')}}}
\\newcommand\\MyKeywordsEn{{{form.get('keywords_en', '')}}}
\\newcommand\\MyShortTitle{{{form.get('title_en', '')[:50]}}}
\\newcommand\\MyAffiliationZh{{}}
\\newcommand\\MyAffiliationEn{{}}
"""
        with open(os.path.join(job_dir, "sections", "metadata.tex"), "w", encoding="utf-8") as f:
            f.write(metadata_content)

        # 6. 複製模板檔案 (包含預設的 references.bib)
        # 注意：一定要先複製，這樣後面使用者上傳的才能覆蓋
        for item in ["split_sections.py", "cjpsych.sty", "main_cjp.tex", "main_apa.tex", "references.bib"]:
            src = os.path.join(TEMPLATE_DIR, item)
            if os.path.exists(src):
                shutil.copy(src, job_dir)

        # 7. 處理使用者上傳的 BibTeX (若有則覆蓋)
        if 'bib_file' in request.files:
            bib = request.files['bib_file']
            if bib.filename:
                # 強制存為 references.bib 以供 LaTeX 讀取
                bib.save(os.path.join(job_dir, "references.bib"))

        # 8. 執行編譯腳本
        target_format = form.get('output_format', 'cjp')
        
        # 使用 subprocess 執行，並設定 cwd 為臨時目錄
        result = subprocess.run(
            ["python", "split_sections.py", "--web-mode", f"--format={target_format}"],
            cwd=job_dir, 
            capture_output=True,
            text=True
        )

        # 檢查是否執行失敗
        if result.returncode != 0:
            print(f"Compilation Failed:\nSTDOUT: {result.stdout}\nSTDERR: {result.stderr}")
            return f"Compilation Error: {result.stderr}", 500

        # 9. 回傳 PDF
        pdf_filename = f"main_{target_format}.pdf"
        pdf_path = os.path.join(job_dir, pdf_filename)
        
        if os.path.exists(pdf_path):
            with open(pdf_path, 'rb') as f:
                pdf_data = f.read()
            from io import BytesIO
            return send_file(
                BytesIO(pdf_data),
                mimetype='application/pdf',
                as_attachment=True,
                download_name=f"thesis_{target_format}.pdf"
            )
        else:
            return "PDF Generation Failed (No Output File)", 500

    except Exception as e:
        import traceback
        traceback.print_exc()
        return f"Worker Internal Error: {str(e)}", 500
        
    finally:
        # 10. 清理戰場 (刪除臨時資料夾)
        shutil.rmtree(job_dir, ignore_errors=True)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5002)